# Generated by Django 5.1.4 on 2024-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdemoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ifsc_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='Dhanlaxmi bank', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ifsc',
            field=models.CharField(default='5214', max_length=11),
        ),
    ]
