# Generated by Django 5.1.4 on 2025-01-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdemoapp', '0002_remove_transaction_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ifsc',
            field=models.CharField(default='', max_length=11),
        ),
    ]
